/*
 * Main public include file
 */
#ifndef __KINESIS_VIDEO_WEBRTC_CLIENT_ERROR__
#define __KINESIS_VIDEO_WEBRTC_CLIENT_ERROR__

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/////////////////////////////////////////////////////
/// Session description init related status codes
/////////////////////////////////////////////////////

/*! \addtogroup SessionDescriptionInitStatusCodes
 * WEBRTC Session Description initialization related codes. Values are derived
 * from STATUS_WEBRTC_BASE (0x55000000)
 *  @{
 */
#define STATUS_WEBRTC_BASE                                         0x55000000
#define STATUS_SESSION_DESCRIPTION_INIT_NOT_OBJECT                 STATUS_WEBRTC_BASE + 0x00000001
#define STATUS_SESSION_DESCRIPTION_INIT_MISSING_SDP_OR_TYPE_MEMBER STATUS_WEBRTC_BASE + 0x00000002
#define STATUS_SESSION_DESCRIPTION_INIT_INVALID_TYPE               STATUS_WEBRTC_BASE + 0x00000003
#define STATUS_SESSION_DESCRIPTION_INIT_MISSING_SDP                STATUS_WEBRTC_BASE + 0x00000004
#define STATUS_SESSION_DESCRIPTION_INIT_MISSING_TYPE               STATUS_WEBRTC_BASE + 0x00000005
#define STATUS_SESSION_DESCRIPTION_INIT_MAX_SDP_LEN_EXCEEDED       STATUS_WEBRTC_BASE + 0x00000006
#define STATUS_SESSION_DESCRIPTION_INVALID_SESSION_DESCRIPTION     STATUS_WEBRTC_BASE + 0x00000007
#define STATUS_SESSION_DESCRIPTION_MISSING_ICE_VALUES              STATUS_WEBRTC_BASE + 0x00000008
#define STATUS_SESSION_DESCRIPTION_MISSING_CERTIFICATE_FINGERPRINT STATUS_WEBRTC_BASE + 0x00000009
#define STATUS_SESSION_DESCRIPTION_MAX_MEDIA_COUNT                 STATUS_WEBRTC_BASE + 0x0000000A
/*!@} */

/////////////////////////////////////////////////////
/// SDP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup SDPStatusCodes
 * WEBRTC SDP packet related codes. Values are derived from STATUS_SDP_BASE
 * (0x56000000)
 *  @{
 */
#define STATUS_SDP_BASE                         STATUS_WEBRTC_BASE + 0x01000000
#define STATUS_SDP_MISSING_ITEMS                STATUS_SDP_BASE + 0x00000001
#define STATUS_SDP_ATTRIBUTES_ERROR             STATUS_SDP_BASE + 0x00000002
#define STATUS_SDP_BANDWIDTH_ERROR              STATUS_SDP_BASE + 0x00000003
#define STATUS_SDP_CONNECTION_INFORMATION_ERROR STATUS_SDP_BASE + 0x00000004
#define STATUS_SDP_EMAIL_ADDRESS_ERROR          STATUS_SDP_BASE + 0x00000005
#define STATUS_SDP_ENCYRPTION_KEY_ERROR         STATUS_SDP_BASE + 0x00000006
#define STATUS_SDP_INFORMATION_ERROR            STATUS_SDP_BASE + 0x00000007
#define STATUS_SDP_MEDIA_NAME_ERROR             STATUS_SDP_BASE + 0x00000008
#define STATUS_SDP_ORIGIN_ERROR                 STATUS_SDP_BASE + 0x00000009
#define STATUS_SDP_PHONE_NUMBER_ERROR           STATUS_SDP_BASE + 0x0000000A
#define STATUS_SDP_TIME_DECRYPTION_ERROR        STATUS_SDP_BASE + 0x0000000B
#define STATUS_SDP_TIMEZONE_ERROR               STATUS_SDP_BASE + 0x0000000C
#define STATUS_SDP_URI_ERROR                    STATUS_SDP_BASE + 0x0000000D
#define STATUS_SDP_VERSION_ERROR                STATUS_SDP_BASE + 0x0000000E
#define STATUS_SDP_ATTRIBUTE_MAX_EXCEEDED       STATUS_SDP_BASE + 0x0000000F
#define STATUS_SDP_NULL_ARG                     STATUS_SDP_BASE + 0x00000010
#define STATUS_SDP_ICE_CANDIDATE_NULL_ARG       STATUS_SDP_BASE + 0x00000011

/*!@} */

/////////////////////////////////////////////////////
/// STUN related status codes
/////////////////////////////////////////////////////

/*! \addtogroup STUNStatusCodes
 * WEBRTC STUN related codes. Values are derived from STATUS_STUN_BASE (0x57000000)
 *  @{
 */
#define STATUS_STUN_BASE                                           STATUS_SDP_BASE + 0x01000000
#define STATUS_STUN_MESSAGE_INTEGRITY_NOT_LAST                     STATUS_STUN_BASE + 0x00000001
#define STATUS_STUN_MESSAGE_INTEGRITY_SIZE_ALIGNMENT               STATUS_STUN_BASE + 0x00000002
#define STATUS_STUN_FINGERPRINT_NOT_LAST                           STATUS_STUN_BASE + 0x00000003
#define STATUS_STUN_MAGIC_COOKIE_MISMATCH                          STATUS_STUN_BASE + 0x00000004
#define STATUS_STUN_INVALID_ADDRESS_ATTRIBUTE_LENGTH               STATUS_STUN_BASE + 0x00000005
#define STATUS_STUN_INVALID_USERNAME_ATTRIBUTE_LENGTH              STATUS_STUN_BASE + 0x00000006
#define STATUS_STUN_INVALID_MESSAGE_INTEGRITY_ATTRIBUTE_LENGTH     STATUS_STUN_BASE + 0x00000007
#define STATUS_STUN_INVALID_FINGERPRINT_ATTRIBUTE_LENGTH           STATUS_STUN_BASE + 0x00000008
#define STATUS_STUN_MULTIPLE_MESSAGE_INTEGRITY_ATTRIBUTES          STATUS_STUN_BASE + 0x00000009
#define STATUS_STUN_MULTIPLE_FINGERPRINT_ATTRIBUTES                STATUS_STUN_BASE + 0x0000000A
#define STATUS_STUN_ATTRIBUTES_AFTER_FINGERPRINT_MESSAGE_INTEGRITY STATUS_STUN_BASE + 0x0000000B
#define STATUS_STUN_MESSAGE_INTEGRITY_AFTER_FINGERPRINT            STATUS_STUN_BASE + 0x0000000C
#define STATUS_STUN_MAX_ATTRIBUTE_COUNT                            STATUS_STUN_BASE + 0x0000000D
#define STATUS_STUN_MESSAGE_INTEGRITY_MISMATCH                     STATUS_STUN_BASE + 0x0000000E
#define STATUS_STUN_FINGERPRINT_MISMATCH                           STATUS_STUN_BASE + 0x0000000F
#define STATUS_STUN_INVALID_PRIORITY_ATTRIBUTE_LENGTH              STATUS_STUN_BASE + 0x00000010
#define STATUS_STUN_INVALID_USE_CANDIDATE_ATTRIBUTE_LENGTH         STATUS_STUN_BASE + 0x00000011
#define STATUS_STUN_INVALID_LIFETIME_ATTRIBUTE_LENGTH              STATUS_STUN_BASE + 0x00000012
#define STATUS_STUN_INVALID_REQUESTED_TRANSPORT_ATTRIBUTE_LENGTH   STATUS_STUN_BASE + 0x00000013
#define STATUS_STUN_INVALID_REALM_ATTRIBUTE_LENGTH                 STATUS_STUN_BASE + 0x00000014
#define STATUS_STUN_INVALID_NONCE_ATTRIBUTE_LENGTH                 STATUS_STUN_BASE + 0x00000015
#define STATUS_STUN_INVALID_ERROR_CODE_ATTRIBUTE_LENGTH            STATUS_STUN_BASE + 0x00000016
#define STATUS_STUN_INVALID_ICE_CONTROL_ATTRIBUTE_LENGTH           STATUS_STUN_BASE + 0x00000017
#define STATUS_STUN_INVALID_CHANNEL_NUMBER_ATTRIBUTE_LENGTH        STATUS_STUN_BASE + 0x00000018
#define STATUS_STUN_INVALID_CHANGE_REQUEST_ATTRIBUTE_LENGTH        STATUS_STUN_BASE + 0x00000019
/*!@} */

/////////////////////////////////////////////////////
/// Networking related status codes
/////////////////////////////////////////////////////

/*! \addtogroup NetworkingStatusCodes
 * WEBRTC Networking related codes. Values are derived from STATUS_NETWORKING_BASE (0x58000000)
 *  @{
 */
#define STATUS_NETWORKING_BASE                     STATUS_STUN_BASE + 0x01000000
#define STATUS_GET_LOCAL_IP_ADDRESSES_FAILED       STATUS_NETWORKING_BASE + 0x00000016
#define STATUS_CREATE_UDP_SOCKET_FAILED            STATUS_NETWORKING_BASE + 0x00000017
#define STATUS_BINDING_SOCKET_FAILED               STATUS_NETWORKING_BASE + 0x00000018
#define STATUS_GET_PORT_NUMBER_FAILED              STATUS_NETWORKING_BASE + 0x00000019
#define STATUS_SEND_DATA_FAILED                    STATUS_NETWORKING_BASE + 0x0000001a
#define STATUS_RESOLVE_HOSTNAME_FAILED             STATUS_NETWORKING_BASE + 0x0000001b
#define STATUS_HOSTNAME_NOT_FOUND                  STATUS_NETWORKING_BASE + 0x0000001c
#define STATUS_SOCKET_CONNECT_FAILED               STATUS_NETWORKING_BASE + 0x0000001d
#define STATUS_CREATE_SSL_FAILED                   STATUS_NETWORKING_BASE + 0x0000001e
#define STATUS_SSL_CONNECTION_FAILED               STATUS_NETWORKING_BASE + 0x0000001f
#define STATUS_SECURE_SOCKET_READ_FAILED           STATUS_NETWORKING_BASE + 0x00000020
#define STATUS_SOCKET_CONNECTION_NOT_READY_TO_SEND STATUS_NETWORKING_BASE + 0x00000021
#define STATUS_SOCKET_CONNECTION_CLOSED_ALREADY    STATUS_NETWORKING_BASE + 0x00000022
#define STATUS_SOCKET_SET_SEND_BUFFER_SIZE_FAILED  STATUS_NETWORKING_BASE + 0x00000023
#define STATUS_GET_SOCKET_FLAG_FAILED              STATUS_NETWORKING_BASE + 0x00000024
#define STATUS_SET_SOCKET_FLAG_FAILED              STATUS_NETWORKING_BASE + 0x00000025
#define STATUS_CLOSE_SOCKET_FAILED                 STATUS_NETWORKING_BASE + 0x00000026
#define STATUS_SOCKET_INVALID_ARG                  STATUS_NETWORKING_BASE + 0x00000027
#define STATUS_RECV_DATA_FAILED                    STATUS_NETWORKING_BASE + 0x00000028
#define STATUS_INIT_NETWORK_FAILED                 STATUS_NETWORKING_BASE + 0x00000029
#define STATUS_NETWORK_CONFIG_ERROR                STATUS_NETWORKING_BASE + 0x0000002A
#define STATUS_NETWORK_SETUP_ERROR                 STATUS_NETWORKING_BASE + 0x0000002B
#define STATUS_NETWORK_SSL_HANDSHAKE_ERROR         STATUS_NETWORKING_BASE + 0x0000002C
#define STATUS_NETWORK_SOCKET_NOT_CONNECTED        STATUS_NETWORKING_BASE + 0x0000002D
#define STATUS_NETWORK_NO_AVAILABLE_RECV_DATA      STATUS_NETWORKING_BASE + 0x0000002E
#define STATUS_NETWORK_SELECT_ERROR                STATUS_NETWORKING_BASE + 0x0000002F

/*!@} */

/////////////////////////////////////////////////////
/// DTLS related status codes
/////////////////////////////////////////////////////

/*! \addtogroup DTLSStatusCodes
 * WEBRTC DTLS related codes. Values are derived from STATUS_DTLS_BASE (0x59000000)
 *  @{
 */
#define STATUS_DTLS_BASE                                  STATUS_NETWORKING_BASE + 0x01000000
#define STATUS_CERTIFICATE_GENERATION_FAILED              STATUS_DTLS_BASE + 0x00000001
#define STATUS_SSL_CTX_CREATION_FAILED                    STATUS_DTLS_BASE + 0x00000002
#define STATUS_SSL_REMOTE_CERTIFICATE_VERIFICATION_FAILED STATUS_DTLS_BASE + 0x00000003
#define STATUS_SSL_PACKET_BEFORE_DTLS_READY               STATUS_DTLS_BASE + 0x00000004
#define STATUS_SSL_UNKNOWN_SRTP_PROFILE                   STATUS_DTLS_BASE + 0x00000005
#define STATUS_SSL_INVALID_CERTIFICATE_BITS               STATUS_DTLS_BASE + 0x00000006
#define STATUS_RSA_CERTIFICATE_GENERATION_FAILED          STATUS_DTLS_BASE + 0x00000007
#define STATUS_ECP_CERTIFICATE_GENERATION_FAILED          STATUS_DTLS_BASE + 0x00000008
#define STATUS_DTLS_NULL_ARG                              STATUS_DTLS_BASE + 0x00000009
#define STATUS_DTLS_DRBG_SEED_FAILED                      STATUS_DTLS_BASE + 0x0000000A
#define STATUS_DTLS_RSA_GEN_KEY_FAILED                    STATUS_DTLS_BASE + 0x0000000B
#define STATUS_DTLS_ECP_GEN_KEY_FAILED                    STATUS_DTLS_BASE + 0x0000000C
#define STATUS_DTLS_MPI_READ_FAILED                       STATUS_DTLS_BASE + 0x0000000D
#define STATUS_DTLS_GEN_TIME_FAILED                       STATUS_DTLS_BASE + 0x0000000E
#define STATUS_DTLS_X509_SET_FAILED                       STATUS_DTLS_BASE + 0x0000000F
#define STATUS_DTLS_SSL_CTX_SETUP_FAILED                  STATUS_DTLS_BASE + 0x00000010
#define STATUS_TLS_SSL_CTX_SETUP_FAILED                   STATUS_DTLS_BASE + 0x00000011
#define STATUS_TLS_SSL_HANDSHAKE_FAILED                   STATUS_DTLS_BASE + 0x00000012
/*!@} */

/////////////////////////////////////////////////////
/// ICE/TURN related status codes
/////////////////////////////////////////////////////

/*! \addtogroup ICEStatusCodes
 * WEBRTC ICE related codes. Values are derived from STATUS_ICE_BASE (0x5a000000)
 *  @{
 */
#define STATUS_ICE_BASE                                                    STATUS_DTLS_BASE + 0x01000000
#define STATUS_ICE_AGENT_NO_SELECTED_CANDIDATE_AVAILABLE                   STATUS_ICE_BASE + 0x00000001
#define STATUS_ICE_CANDIDATE_STRING_MISSING_PORT                           STATUS_ICE_BASE + 0x00000002
#define STATUS_ICE_CANDIDATE_STRING_MISSING_IP                             STATUS_ICE_BASE + 0x00000003
#define STATUS_ICE_CANDIDATE_STRING_INVALID_IP                             STATUS_ICE_BASE + 0x00000004
#define STATUS_ICE_CANDIDATE_STRING_IS_TCP                                 STATUS_ICE_BASE + 0x00000005
#define STATUS_ICE_FAILED_TO_COMPUTE_MD5_FOR_LONG_TERM_CREDENTIAL          STATUS_ICE_BASE + 0x00000006
#define STATUS_ICE_URL_INVALID_PREFIX                                      STATUS_ICE_BASE + 0x00000007
#define STATUS_ICE_URL_TURN_MISSING_USERNAME                               STATUS_ICE_BASE + 0x00000008
#define STATUS_ICE_URL_TURN_MISSING_CREDENTIAL                             STATUS_ICE_BASE + 0x00000009
#define STATUS_ICE_AGENT_STATE_CHANGE_FAILED                               STATUS_ICE_BASE + 0x0000000a
#define STATUS_ICE_NO_LOCAL_CANDIDATE_AVAILABLE_AFTER_GATHERING_TIMEOUT    STATUS_ICE_BASE + 0x0000000b
#define STATUS_ICE_AGENT_TERMINATED_ALREADY                                STATUS_ICE_BASE + 0x0000000c
#define STATUS_ICE_NO_CONNECTED_CANDIDATE_PAIR                             STATUS_ICE_BASE + 0x0000000d
#define STATUS_ICE_CANDIDATE_PAIR_LIST_EMPTY                               STATUS_ICE_BASE + 0x0000000e
#define STATUS_ICE_NOMINATED_CANDIDATE_NOT_CONNECTED                       STATUS_ICE_BASE + 0x00000010
#define STATUS_ICE_CANDIDATE_INIT_MALFORMED                                STATUS_ICE_BASE + 0x00000011
#define STATUS_ICE_CANDIDATE_MISSING_CANDIDATE                             STATUS_ICE_BASE + 0x00000012
#define STATUS_ICE_FAILED_TO_NOMINATE_CANDIDATE_PAIR                       STATUS_ICE_BASE + 0x00000013
#define STATUS_ICE_MAX_REMOTE_CANDIDATE_COUNT_EXCEEDED                     STATUS_ICE_BASE + 0x00000014
#define STATUS_ICE_INVALID_STATE                                           STATUS_ICE_BASE + 0x0000001c
#define STATUS_ICE_NO_LOCAL_HOST_CANDIDATE_AVAILABLE                       STATUS_ICE_BASE + 0x0000001d
#define STATUS_ICE_NO_NOMINATED_VALID_CANDIDATE_PAIR_AVAILABLE             STATUS_ICE_BASE + 0x0000001e
#define STATUS_TURN_CONNECTION_NO_HOST_INTERFACE_FOUND                     STATUS_ICE_BASE + 0x0000001f
#define STATUS_TURN_CONNECTION_STATE_TRANSITION_TIMEOUT                    STATUS_ICE_BASE + 0x00000020
#define STATUS_TURN_CONNECTION_FAILED_TO_CREATE_PERMISSION                 STATUS_ICE_BASE + 0x00000021
#define STATUS_TURN_CONNECTION_FAILED_TO_BIND_CHANNEL                      STATUS_ICE_BASE + 0x00000022
#define STATUS_TURN_NEW_DATA_CHANNEL_MSG_HEADER_BEFORE_PREVIOUS_MSG_FINISH STATUS_ICE_BASE + 0x00000023
#define STATUS_TURN_MISSING_CHANNEL_DATA_HEADER                            STATUS_ICE_BASE + 0x00000024
#define STATUS_ICE_FAILED_TO_RECOVER_FROM_DISCONNECTION                    STATUS_ICE_BASE + 0x00000025
#define STATUS_ICE_NO_AVAILABLE_ICE_CANDIDATE_PAIR                         STATUS_ICE_BASE + 0x00000026
#define STATUS_TURN_CONNECTION_PEER_NOT_USABLE                             STATUS_ICE_BASE + 0x00000027
#define STATUS_ICE_SERVER_INDEX_INVALID                                    STATUS_ICE_BASE + 0x00000028
#define STATUS_ICE_NOT_ENOUGH_MEMORY                                       STATUS_ICE_BASE + 0x00000029
#define STATUS_ICE_NULL_ARG                                                STATUS_ICE_BASE + 0x0000002A
#define STATUS_ICE_NULL_NOMINATED_CANDIDATE_PAIR                           STATUS_ICE_BASE + 0x0000002B
#define STATUS_TURN_CONNECTION_CHECK_CONN_TIMEOUT                          STATUS_ICE_BASE + 0x0000002C
#define STATUS_TURN_CONNECTION_GET_CREDENTIALS_TIMEOUT                     STATUS_ICE_BASE + 0x0000002D
#define STATUS_TURN_CONNECTION_ALLOCATION_TIMEOUT                          STATUS_ICE_BASE + 0x0000002E
#define STATUS_ICE_CANDIDATE_STRING_MISSING_TYPE                           STATUS_ICE_BASE + 0x0000002F
/*!@} */

/////////////////////////////////////////////////////
/// SRTP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup SRTPStatusCodes
 * WEBRTC SRTP related codes. Values are derived from STATUS_SRTP_BASE (0x5b000000)
 *  @{
 */
#define STATUS_SRTP_BASE                             STATUS_ICE_BASE + 0x01000000
#define STATUS_SRTP_DECRYPT_FAILED                   STATUS_SRTP_BASE + 0x00000001
#define STATUS_SRTP_ENCRYPT_FAILED                   STATUS_SRTP_BASE + 0x00000002
#define STATUS_SRTP_TRANSMIT_SESSION_CREATION_FAILED STATUS_SRTP_BASE + 0x00000003
#define STATUS_SRTP_RECEIVE_SESSION_CREATION_FAILED  STATUS_SRTP_BASE + 0x00000004
#define STATUS_SRTP_INIT_FAILED                      STATUS_SRTP_BASE + 0x00000005
#define STATUS_SRTP_NOT_READY_YET                    STATUS_SRTP_BASE + 0x00000006
#define STATUS_SRTCP_DECRYPT_FAILED                  STATUS_SRTP_BASE + 0x00000007
#define STATUS_SRTCP_ENCRYPT_FAILED                  STATUS_SRTP_BASE + 0x00000008
/*!@} */

/////////////////////////////////////////////////////
/// RTP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup RTPStatusCodes
 * WEBRTC RTP related codes. Values are derived from STATUS_RTP_BASE (0x5c000000)
 *  @{
 */
#define STATUS_RTP_BASE                   STATUS_SRTP_BASE + 0x01000000
#define STATUS_RTP_INPUT_PACKET_TOO_SMALL STATUS_RTP_BASE + 0x00000001
#define STATUS_RTP_INPUT_MTU_TOO_SMALL    STATUS_RTP_BASE + 0x00000002
#define STATUS_RTP_INVALID_NALU           STATUS_RTP_BASE + 0x00000003
#define STATUS_RTP_INVALID_EXTENSION_LEN  STATUS_RTP_BASE + 0x00000004
#define STATUS_RTP_NULL_ARG               STATUS_RTP_BASE + 0x00000005
#define STATUS_RTP_BUFFER_TOO_SMALL       STATUS_RTP_BASE + 0x00000006
#define STATUS_RTP_NOT_ENOUGH_MEMORY      STATUS_RTP_BASE + 0x00000007
/*!@} */

/////////////////////////////////////////////////////
/// Signaling related status codes
/////////////////////////////////////////////////////

/*! \addtogroup SignalingStatusCodes
 * WEBRTC Signaling related codes. Values are derived from STATUS_SIGNALING_BASE (0x5d000000)
 *  @{
 */
#define STATUS_SIGNALING_BASE                                      STATUS_RTP_BASE + 0x01000000
#define STATUS_SIGNALING_INVALID_READY_STATE                       STATUS_SIGNALING_BASE + 0x00000001
#define STATUS_SIGNALING_GET_TOKEN_CALL_FAILED                     STATUS_SIGNALING_BASE + 0x00000002
#define STATUS_SIGNALING_DESCRIBE_CALL_FAILED                      STATUS_SIGNALING_BASE + 0x00000003
#define STATUS_SIGNALING_CREATE_CALL_FAILED                        STATUS_SIGNALING_BASE + 0x00000004
#define STATUS_SIGNALING_GET_ENDPOINT_CALL_FAILED                  STATUS_SIGNALING_BASE + 0x00000005
#define STATUS_SIGNALING_GET_ICE_CONFIG_CALL_FAILED                STATUS_SIGNALING_BASE + 0x00000006
#define STATUS_SIGNALING_READY_CALLBACK_FAILED                     STATUS_SIGNALING_BASE + 0x00000007
#define STATUS_SIGNALING_CONNECT_CALL_FAILED                       STATUS_SIGNALING_BASE + 0x00000008
#define STATUS_SIGNALING_CONNECTED_CALLBACK_FAILED                 STATUS_SIGNALING_BASE + 0x00000009
#define STATUS_SIGNALING_INVALID_CHANNEL_INFO_VERSION              STATUS_SIGNALING_BASE + 0x0000000A
#define STATUS_SIGNALING_INVALID_SIGNALING_CALLBACKS_VERSION       STATUS_SIGNALING_BASE + 0x0000000B
#define STATUS_SIGNALING_INVALID_CHANNEL_NAME_LENGTH               STATUS_SIGNALING_BASE + 0x0000000C
#define STATUS_SIGNALING_INVALID_CHANNEL_ARN_LENGTH                STATUS_SIGNALING_BASE + 0x0000000D
#define STATUS_SIGNALING_INVALID_REGION_LENGTH                     STATUS_SIGNALING_BASE + 0x0000000E
#define STATUS_SIGNALING_INVALID_CPL_LENGTH                        STATUS_SIGNALING_BASE + 0x0000000F
#define STATUS_SIGNALING_INVALID_CERTIFICATE_PATH_LENGTH           STATUS_SIGNALING_BASE + 0x00000010
#define STATUS_SIGNALING_INVALID_AGENT_POSTFIX_LENGTH              STATUS_SIGNALING_BASE + 0x00000011
#define STATUS_SIGNALING_INVALID_AGENT_LENGTH                      STATUS_SIGNALING_BASE + 0x00000012
#define STATUS_SIGNALING_INVALID_KMS_KEY_LENGTH                    STATUS_SIGNALING_BASE + 0x00000013
#define STATUS_SIGNALING_LWS_CREATE_CONTEXT_FAILED                 STATUS_SIGNALING_BASE + 0x00000014
#define STATUS_SIGNALING_LWS_CLIENT_CONNECT_FAILED                 STATUS_SIGNALING_BASE + 0x00000015
#define STATUS_SIGNALING_CHANNEL_BEING_DELETED                     STATUS_SIGNALING_BASE + 0x00000016
#define STATUS_SIGNALING_INVALID_CLIENT_INFO_VERSION               STATUS_SIGNALING_BASE + 0x00000017
#define STATUS_SIGNALING_INVALID_CLIENT_INFO_CLIENT_LENGTH         STATUS_SIGNALING_BASE + 0x00000018
#define STATUS_SIGNALING_MAX_ICE_CONFIG_COUNT                      STATUS_SIGNALING_BASE + 0x00000019
#define STATUS_SIGNALING_MAX_ICE_URI_COUNT                         STATUS_SIGNALING_BASE + 0x0000001A
#define STATUS_SIGNALING_MAX_ICE_URI_LEN                           STATUS_SIGNALING_BASE + 0x0000001B
#define STATUS_SIGNALING_NO_CONFIG_SPECIFIED                       STATUS_SIGNALING_BASE + 0x0000001C
#define STATUS_SIGNALING_INVALID_ICE_CONFIG_INFO_VERSION           STATUS_SIGNALING_BASE + 0x0000001D
#define STATUS_SIGNALING_NO_CONFIG_URI_SPECIFIED                   STATUS_SIGNALING_BASE + 0x0000001E
#define STATUS_SIGNALING_NO_ARN_RETURNED_ON_CREATE                 STATUS_SIGNALING_BASE + 0x0000001F
#define STATUS_SIGNALING_MISSING_ENDPOINTS_IN_GET_ENDPOINT         STATUS_SIGNALING_BASE + 0x00000020
#define STATUS_SIGNALING_INVALID_MESSAGE_TYPE                      STATUS_SIGNALING_BASE + 0x00000021
#define STATUS_SIGNALING_INVALID_SIGNALING_MESSAGE_VERSION         STATUS_SIGNALING_BASE + 0x00000022
#define STATUS_SIGNALING_NO_PEER_CLIENT_ID_IN_MESSAGE              STATUS_SIGNALING_BASE + 0x00000023
#define STATUS_SIGNALING_MESSAGE_DELIVERY_FAILED                   STATUS_SIGNALING_BASE + 0x00000024
#define STATUS_SIGNALING_MAX_MESSAGE_LEN_AFTER_ENCODING            STATUS_SIGNALING_BASE + 0x00000025
#define STATUS_SIGNALING_RECEIVE_BINARY_DATA_NOT_SUPPORTED         STATUS_SIGNALING_BASE + 0x00000026
#define STATUS_SIGNALING_RECEIVE_EMPTY_DATA_NOT_SUPPORTED          STATUS_SIGNALING_BASE + 0x00000027
#define STATUS_SIGNALING_RECEIVED_MESSAGE_LARGER_THAN_MAX_DATA_LEN STATUS_SIGNALING_BASE + 0x00000028
#define STATUS_SIGNALING_INVALID_PAYLOAD_LEN_IN_MESSAGE            STATUS_SIGNALING_BASE + 0x00000029
#define STATUS_SIGNALING_NO_PAYLOAD_IN_MESSAGE                     STATUS_SIGNALING_BASE + 0x0000002A
#define STATUS_SIGNALING_DUPLICATE_MESSAGE_BEING_SENT              STATUS_SIGNALING_BASE + 0x0000002B
#define STATUS_SIGNALING_ICE_TTL_LESS_THAN_GRACE_PERIOD            STATUS_SIGNALING_BASE + 0x0000002C
#define STATUS_SIGNALING_DISCONNECTED_CALLBACK_FAILED              STATUS_SIGNALING_BASE + 0x0000002D
#define STATUS_SIGNALING_INVALID_MESSAGE_TTL_VALUE                 STATUS_SIGNALING_BASE + 0x0000002E
#define STATUS_SIGNALING_ICE_CONFIG_REFRESH_FAILED                 STATUS_SIGNALING_BASE + 0x0000002F
#define STATUS_SIGNALING_RECONNECT_FAILED                          STATUS_SIGNALING_BASE + 0x00000030
#define STATUS_SIGNALING_DELETE_CALL_FAILED                        STATUS_SIGNALING_BASE + 0x00000031
#define STATUS_SIGNALING_INVALID_METRICS_VERSION                   STATUS_SIGNALING_BASE + 0x00000032
#define STATUS_SIGNALING_INVALID_ICE_CONFIG_COUNT                  STATUS_SIGNALING_BASE + 0x00000033
#define STATUS_SIGNALING_NULL_ARG                                  STATUS_SIGNALING_BASE + 0x00000034
#define STATUS_SIGNALING_CREATE_THREAD_FAILED                      STATUS_SIGNALING_BASE + 0x00000035
#define STATUS_SIGNALING_CREATE_MSGQ_FAILED                        STATUS_SIGNALING_BASE + 0x00000036
#define STATUS_SIGNALING_DISPATCH_FAILED                           STATUS_SIGNALING_BASE + 0x00000037

/*!@} */

/////////////////////////////////////////////////////
/// Peer connection related status codes
/////////////////////////////////////////////////////

/*! \addtogroup PeerConnectionStatusCodes
 * WEBRTC STUN related codes. Values are derived from STATUS_PEERCONNECTION_BASE
 * (0x5e000000)
 *  @{
 */
#define STATUS_PEERCONNECTION_BASE                                     STATUS_SIGNALING_BASE + 0x01000000
#define STATUS_PEERCONNECTION_CREATE_ANSWER_WITHOUT_REMOTE_DESCRIPTION STATUS_PEERCONNECTION_BASE + 0x00000001
#define STATUS_PEERCONNECTION_CODEC_INVALID                            STATUS_PEERCONNECTION_BASE + 0x00000002
#define STATUS_PEERCONNECTION_CODEC_MAX_EXCEEDED                       STATUS_PEERCONNECTION_BASE + 0x00000003
/*!@} */

/////////////////////////////////////////////////////
/// SCTP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup SCTPStatusCodes
 * WEBRTC SCTP related codes. Values are derived from STATUS_STUN_BASE (0x5f000000)
 *  @{
 */
#define STATUS_SCTP_BASE                    STATUS_PEERCONNECTION_BASE + 0x01000000
#define STATUS_SCTP_SESSION_SETUP_FAILED    STATUS_SCTP_BASE + 0x00000001
#define STATUS_SCTP_INVALID_DCEP_PACKET     STATUS_SCTP_BASE + 0x00000002
#define STATUS_SCTP_SO_NON_BLOCKING_FAILED  STATUS_SCTP_BASE + 0x00000003
#define STATUS_SCTP_SO_CREATE_FAILED        STATUS_SCTP_BASE + 0x00000004
#define STATUS_SCTP_SO_BIND_FAILED          STATUS_SCTP_BASE + 0x00000005
#define STATUS_SCTP_SO_CONNECT_FAILED       STATUS_SCTP_BASE + 0x00000006
#define STATUS_SCTP_SO_LINGER_FAILED        STATUS_SCTP_BASE + 0x00000007
#define STATUS_SCTP_SO_NODELAY_FAILED       STATUS_SCTP_BASE + 0x00000008
#define STATUS_SCTP_EVENT_FAILED            STATUS_SCTP_BASE + 0x00000009
#define STATUS_SCTP_INITMSG_FAILED          STATUS_SCTP_BASE + 0x0000000A
#define STATUS_SCTP_PEER_ADDR_PARAMS_FAILED STATUS_SCTP_BASE + 0x0000000B

/*!@} */

/////////////////////////////////////////////////////
/// RTCP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup RTCPStatusCodes
 * WEBRTC RTCP related codes. Values are derived from STATUS_RTCP_BASE (0x60000000)
 *  @{
 */
#define STATUS_RTCP_BASE                         STATUS_SCTP_BASE + 0x01000000
#define STATUS_RTCP_INPUT_PACKET_TOO_SMALL       STATUS_RTCP_BASE + 0x00000001
#define STATUS_RTCP_INPUT_PACKET_INVALID_VERSION STATUS_RTCP_BASE + 0x00000002
#define STATUS_RTCP_INPUT_PACKET_LEN_MISMATCH    STATUS_RTCP_BASE + 0x00000003
#define STATUS_RTCP_INPUT_NACK_LIST_INVALID      STATUS_RTCP_BASE + 0x00000004
#define STATUS_RTCP_INPUT_SSRC_INVALID           STATUS_RTCP_BASE + 0x00000005
#define STATUS_RTCP_INPUT_PARTIAL_PACKET         STATUS_RTCP_BASE + 0x00000006
#define STATUS_RTCP_INPUT_REMB_TOO_SMALL         STATUS_RTCP_BASE + 0x00000007
#define STATUS_RTCP_INPUT_REMB_INVALID           STATUS_RTCP_BASE + 0x00000008
#define STATUS_RTCP_NULL_ARG                     STATUS_RTCP_BASE + 0x00000009
/*!@} */

/////////////////////////////////////////////////////
/// Rolling buffer related status codes
/////////////////////////////////////////////////////

/*! \addtogroup RollingBufferStatusCodes
 * WEBRTC Rolling Buffer related codes. Values are derived from STATUS_ROLLING_BUFFER_BASE
 * (0x61000000)
 *  @{
 */
#define STATUS_ROLLING_BUFFER_BASE         STATUS_RTCP_BASE + 0x01000000
#define STATUS_ROLLING_BUFFER_NOT_IN_RANGE STATUS_ROLLING_BUFFER_BASE + 0x00000001
/*!@} */

/////////////////////////////////////////////////////
/// AWSSignerV4 related status codes
/////////////////////////////////////////////////////

/*! \addtogroup AWSSignerV4StatusCodes
 * WEBRTC AWSSignerV4 related codes. Values are derived from STATUS_AWS_SIGNER_BASE (0x62000000)
 *  @{
 */
#define STATUS_AWS_SIGNER_BASE                   STATUS_ROLLING_BUFFER_BASE + 0x01000000
#define STATUS_AWS_SIGNER_FAIL_TO_CALCULATE_HASH STATUS_AWS_SIGNER_BASE + 0x00000001
/*!@} */

/////////////////////////////////////////////////////
/// Json related status codes
/////////////////////////////////////////////////////

/*! \addtogroup JsonStatusCodes
 * WEBRTC json related codes. Values are derived from STATUS_JSON_BASE (0x63000000)
 *  @{
 */
#define STATUS_JSON_BASE        STATUS_AWS_SIGNER_BASE + 0x01000000
#define STATUS_JSON_PARSE_ERROR STATUS_JSON_BASE + 0x00000001
/*!@} */

/////////////////////////////////////////////////////
/// http related status codes
/////////////////////////////////////////////////////

/*! \addtogroup httpStatusCodes
 * WEBRTC http related codes. Values are derived from STATUS_JSON_BASE (0x64000000)
 *  @{
 */
#define STATUS_HTTP_BASE                      STATUS_JSON_BASE + 0x01000000
#define STATUS_HTTP_RES_NOT_FOUND_ERROR       STATUS_HTTP_BASE + 0x00000001
#define STATUS_HTTP_REST_EXCEPTION_ERROR      STATUS_HTTP_BASE + 0x00000002
#define STATUS_HTTP_REST_NOT_AUTHORIZED_ERROR STATUS_HTTP_BASE + 0x00000003
#define STATUS_HTTP_REST_UNKNOWN_ERROR        STATUS_HTTP_BASE + 0x00000004
/*!@} */

/////////////////////////////////////////////////////
/// wss related status codes
/////////////////////////////////////////////////////

/*! \addtogroup wssStatusCodes
 * WEBRTC wss related codes. Values are derived from STATUS_JSON_BASE (0x65000000)
 *  @{
 */
#define STATUS_WSS_BASE                      STATUS_HTTP_BASE + 0x01000000
#define STATUS_WSS_CLIENT_SEND_FAILED        STATUS_WSS_BASE + 0x00000001
#define STATUS_WSS_CLIENT_RECV_FAILED        STATUS_WSS_BASE + 0x00000001
#define STATUS_WSS_UPGRADE_CONNECTION_ERROR  STATUS_WSS_BASE + 0x00000002
#define STATUS_WSS_UPGRADE_PROTOCOL_ERROR    STATUS_WSS_BASE + 0x00000003
#define STATUS_WSS_ACCEPT_KEY_ERROR          STATUS_WSS_BASE + 0x00000004
#define STATUS_WSS_GENERATE_CLIENT_KEY_ERROR STATUS_WSS_BASE + 0x00000005
#define STATUS_WSS_GENERATE_ACCEPT_KEY_ERROR STATUS_WSS_BASE + 0x00000005
#define STATUS_WSS_VALIDATE_ACCEPT_KEY_ERROR STATUS_WSS_BASE + 0x00000006
#define STATUS_WSS_GENERATE_RANDOM_NUM_ERROR STATUS_WSS_BASE + 0x00000007
/*!@} */

#ifdef __cplusplus
}
#endif
#endif /* __KINESIS_VIDEO_WEBRTC_CLIENT_ERROR__ */
